### PR TITLE
React/week3 homework 

### PR DESCRIPTION
**Pull request by shpomp**
--
--
82f9b31 and  05b036a should not be here, sorry 😿 
look at [730d774](https://github.com/shpomp/hyf-homework/commit/730d774c314771583d1566ffe5081ce835a4e69b) please 🙏🏽

### CODE REVIEW

**Comment by cecastosic** [comment]
@shpomp Please clean the PR to have only files related to week 3 homework. There are 142 files. 🙁

**Review by cecastosic — CHANGES_REQUESTED** [review]
Please don't merge this PR before you clean it to include only files related to week3 homework. 
Good reading for having the right structure for a React app https://reactjs.org/docs/faq-structure.html

**Comment by shpomp** [comment]
> buttons look like they are disabled, I would suggest changing CSS 🙂

not sure what this means - they are not disabled in any way 🤷🏽‍♀️

**Comment by shpomp** [comment]
> const saveTask = (id) => {
> setEditing(false);
> };
> no need for setState here at all, since you are changing state on onChange, you should just show the value [730d774#r51779560](https://github.com/shpomp/hyf-homework/commit/730d774c314771583d1566ffe5081ce835a4e69b#r51779560)

I am changing the display according to editing mode, so I believe I do need to set state here :)

**Comment by shpomp** [comment]
Thank you very much @cecastosic ! ❤️  ☀️ 
Some comments were very vague though and made it difficult to grasp what exactly should be changed, how and why 🙈  If you could be a bit more specific next time, that would be very very helpful! 🙏🏽

**Comment by cecastosic** [comment]
@shpomp sorry to hear that my feedback wasn't clear enough. You can always ask for more details if you need them. I am happy to help. 🙂 
You should also be careful and not to make PRs that have 142 files changed. It is almost impossible to review them. I can still see that there are 78 files changed in this PR, and it should be a maximum of 10 files for one-week homework. You could also close this PR and make another one with only homework related files if you couldn't find a way how to fix it. You could also ask for help. Commit messages that are one letter long shouldn't be visible. You can always do interactive rebase to have a clear PR https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history .

**Comment by cecastosic** [comment]
> > buttons look like they are disabled, I would suggest changing CSS 🙂
> 
> not sure what this means - they are not disabled in any way 🤷🏽‍♀️

That means that they look like they are disabled because you chose a light pink colour for them. And I suggested changing the CSS style for them since I put a comment in the CSS file. Hope it is more clear now 🙂

**Pull request merged**
